[colors.primary]
#background = "0x000000"
#foreground = "0xffffff"
foreground= "0x000000"
background = "0xffffff"

[font]
size = 12

offset = {x = 0, y = 5}

[font.normal]
# family = "Maple Mono NF CN"
family = "Jetbrains Mono NF"
style = "SemiBold"

[window]
opacity = 0.93
blur = true
