InlayHints:
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes

CompileFlags:
  Add: [-Wall]

Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [clang-*, performance-*, google-*, concurrency-*, bugprone-*]

---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Add: [-std=c++20]
  Compiler: clang++
Diagnostics:
  ClangTidy:
    Add: [cppcoreguidelines-*, modernize-*,]

---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Add: [-std=c17]
  Compiler: clang
